### ISSUE TITLE
feat: crear un servicio que conecte con la API de noticias y devuelva X cantidad de estas

### ISSUE THREAD

**Issue by Joadevy** [ProyectoTaller2023/Newslify#17]
No queremos persistir todas las noticias que vienen de la API asi que no tendriamos que mapear nada a la base de datos. Lo que estamos haciendo aca es llamar desde el backend a la API y devolverle a nuestro frontend la info de las noticias en un JSON probablemente.

 Esto se podria resolver directamente desde el frontend llamando a la API y sin necesidad de pasar por backend pero al forzar a pasar por backend podriamos hacer ciertos controles, filtrar data, etc antes de devolver (saber si la noticia fue leida o no por ejemplo) e implementar algun patron para no acoplarnos a la API en si (Adapter-Proxy).

**Comment by gianbarreto** [comment]
terminado
